# Generated by Django 3.0.3 on 2020-02-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
