# Generated by Django 3.0.3 on 2020-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_custuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='department',
        ),
        migrations.AddField(
            model_name='custuser',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
